"""initial schema — backend + ai-data tables

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-13

Creates every table this project owns in one shot: `users`,
`student_profiles`, `questions`, `assessments`, `answers`, `study_plans`,
`learning_sessions`, `progress_records` (backend-owned) plus
`topic_mastery`, `ai_memory`, `ai_logs`, `concept_embeddings` (ai-data-
owned) — via `app.database.metadata.get_merged_metadata()`, the same
merge logic `alembic/env.py` uses for autogenerate, so this migration and
future autogenerated ones are always diffing against the same target.

Uses `metadata.create_all()`/`drop_all()` rather than a table-by-table
`op.create_table()` — a standard, well-supported Alembic pattern for a
project's very first migration, since there's no prior schema to diff
against yet. Future schema changes should use
`alembic revision --autogenerate` as normal, which will diff against
whatever's actually in the target database.
"""

from __future__ import annotations

from alembic import op

from app.database.metadata import get_merged_metadata

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    metadata = get_merged_metadata()
    bind = op.get_bind()
    metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    metadata = get_merged_metadata()
    bind = op.get_bind()
    metadata.drop_all(bind=bind, checkfirst=True)
